hub:
  type: nats
  protocols:
    nats:
      servers:
      - localhost:4222
    websockets:
      servers:
      - ws://localhost:4243

partitioning:
  timePartition:
    aggregationPeriodInMin: 10
    maxCapacity: 20000000
  dataPartition:
    # type: id
    # type: idGroup
    # groupSize: 10
    type: geohash
    hashLength: 5

generator:
  logging:
    enabled: true
    level: debug
  generatorCount: 1
  vehicleCount: 150
  maxNumberOfEvents: 100000
  refreshIntervalInSecs: 5
  realtime: false
  sendFlush: true
  terminateCollector: true
  startDate: '2024-01-01T00:00:00-05:00'
  map:
    topLeftOrigin:
        # https://www.google.ca/maps/@45.6656598,-74.0651269,11.76z?entry=ttu
        lat: 45.6656598
        lon: -74.0651269
        alt: 11.76
    widthInKm: 40
    heightInKm: 20
  zoneSize:
    widthInKm: 10
    heightInKm: 10

collector:
  verbose: false
  logging:
    enabled: true
    level: debug
  collectorCount: 4
  geohashLength: 7 # 152.9m x 152.4m
  eventStore:
    type: noop # noop, memory, duckdb
  output:
    # type: noop
    type: file
    folder: ../../output/data
    flatLayout: true
    formats:
    - parquet
    # - csv
    # - arrow

querier:
  logging:
    enabled: true
    level: debug
  querierCount: 1
  autoStart: true
  defaultTimeoutInMS: 30000
  
viewer:
  logging:
    enabled: true
    level: debug
