hub:
  type: nats
  protocols:
    nats:
      servers:
      - localhost:4222
    websockets:
      servers:
      - ws://localhost:4243

partitioning:
  timePartition:
    aggregationPeriodInMin: 10
    maxCapacity: 200000
  dataPartition:
    # type: id
    # type: idGroup
    # groupSize: 10
    type: geohash
    hashLength: 5

generator:
  logging:
    enabled: true
    level: debug
  generatorCount: 1
  vehicleCount: 10000
  maxNumberOfEvents: 1000000
  refreshIntervalInSecs: 5
  realtime: false
  sendFlush: true
  terminateCollector: true

collector:
  verbose: false
  logging:
    enabled: true
    level: debug
  collectorCount: 1
  geohashLength: 7 # 152.9m x 152.4m
  eventStore:
    type: noop # noop, memory, duckdb
  output:
    # type: noop
    type: file
    folder: ./output/data
    flatLayout: true
    formats:
    - parquet

viewer:
  logging:
    enabled: true
    level: debug
