hub:
  type: nats
  protocols:
    nats:
      servers:
      - localhost:4222
    websockets:
      servers:
      - ws://localhost:4243

partitioning:
  timePartition:
    aggregationPeriodInMin: 10
    maxCapacity: 100000
    maxActivePartitions: 2
  dataPartition:
    # type: id
    # type: idGroup
    # groupSize: 10
    type: geohash
    hashLength: 5 # 4.9km x 4.9km

generator:
  logging:
    enabled: true
    level: debug
  instances: 2
  vehicleCount: 1500
  maxNumberOfEvents: 5000000
  refreshIntervalInSecs: 5
  realtime: false
  sendFlush: true
  terminateCollector: true
  startDate: '2024-01-01T00:00:00-05:00'
  map:
    topLeftOrigin:
        # https://www.google.ca/maps/@45.6656598,-74.0651269,11.76z?entry=ttu
        lat: 45.6656598
        lon: -74.0651269
        alt: 11.76
    widthInKm: 40
    heightInKm: 20
  zoneSize:
    widthInKm: 10
    heightInKm: 10
  vehicleTypes:
    - Ambulance
    - Audi
    - Black_viper
    - Car
    - Mini_truck
    - Mini_van
    - Police
    - taxi
    - truck

collector:
  verbose: false
  logging:
    enabled: true
    level: debug
  instances: 5
  geohashLength: 7 # 152.9m x 152.4m
  eventStore:
    type: noop # noop, memory, duckdb
  output:
    # type: noop
    type: file
    folder: ../../output/data
    flatLayout: false
    formats:
    - parquet
    # - csv
    # - arrow

querier:
  logging:
    enabled: true
    level: debug
  instances: 1
  autoStart: true
  defaultTimeoutInMS: 30000
  dataFormat: parquet
  
viewer:
  logging:
    enabled: true
    level: debug
