hub:
  type: nats
  enableProtoBuf: true
  protocols:
    nats:
      servers:
      - localhost:4222
    websockets:
      servers:
      - ws://localhost:4243
  # type: azureServiceBus
  # enableProtoBuf: true
  # connectionString: Endpoint=sb://foobar.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=redacted

partitioning:
  timePartition:
    aggregationPeriodInMin: 10
    maxCapacity: 300000
    maxActivePartitions: 2
  dataPartition:
    # type: id
    # type: idGroup
    # groupSize: 10
    type: geohash
    hashLength: 5 # 4.9km x 4.9km

backpressure:
  enabled: true
  notificationThreshold: 1000
  notificationPeriodInMS: 100
  waitTimeoutInMS: 10000
  waitThreshold: 1000

chaosEngineering:
  enabled: false
  messageReadDelayInMS: 100
  messageWriteDelayInMS: 0

generator:
  logging:
    enabled: true
    level: debug
  instances: 1
  httpPort: 7710
  vehicleCount: 1500
  maxNumberOfEvents: 5000000
  messageChunkSize: 5000
  refreshIntervalInSecs: 5
  realtime: false
  sendFlush: true
  startDate: '2024-01-01T00:00:00-05:00'
  map:
    topLeftOrigin:
        # https://www.google.ca/maps/@45.6656598,-74.0651269,11.76z?entry=ttu
        lat: 45.6656598
        lon: -74.0651269
        alt: 11.76
    widthInKm: 40
    heightInKm: 20
  zoneSize:
    widthInKm: 10
    heightInKm: 10
  vehicleTypes:
    - Ambulance
    - Audi
    - Black_viper
    - Car
    - Mini_truck
    - Mini_van
    - Police
    - taxi
    - truck

collector:
  logging:
    enabled: true
    level: info
  instances: 3
  httpPort: 7720
  geohashLength: 7 # 152.9m x 152.4m
  eventStore:
    type: noop # noop, memory, duckdb
  output:
    overwriteExistingFiles: false
    flatLayout: true
    formats:
    - parquet
    # - csv
    # - arrow
    storage:
      # type: noop
      # type: s3

      # type: azure-blob
      # containerName: events

      type: file
      folder: ../../output/data

finder:
  logging:
    enabled: true
    level: info
  instances: 3
  httpPort: 7730
  defaultTimeoutInMS: 30000
  dataFormat: parquet
  parallelSearch: true
  useChunking: false
  messageChunkSize: 5000

viewer:
  logging:
    enabled: true
    level: debug
