hub:
  type: nats
  enableProtoBuf: true
  protocols:
    nats:
      servers:
      - localhost:4222
    websockets:
      servers:
      - ws://localhost:4243
  # type: azureServiceBus
  # enableProtoBuf: true
  # connectionString: Endpoint=sb://foobar.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<redacted>

partitioning:
  timePartition:
    aggregationPeriodInMin: 10
    maxCapacity: 300000
    maxActivePartitions: 2
  dataPartition:
    # type: id
    # type: idGroup
    # groupSize: 10
    type: geohash
    hashLength: 5 # 4.9km x 4.9km

backpressure:
  enabled: true
  notificationThreshold: 1000
  notificationPeriodInMS: 100
  waitTimeoutInMS: 60000
  waitThreshold: 1000

chaosEngineering:
  enabled: false
  messageReadDelayInMS: 100
  messageWriteDelayInMS: 0

generator:
  logging:
    enabled: true
    level: debug
  instances: 1
  httpPort: 7710
  vehicleCount: 1500
  maxNumberOfEvents: 5000000
  messageChunkSize: 5000
  refreshIntervalInSecs: 5
  realtime: false
  sendFlush: true
  startDate: '2024-01-01T00:00:00-05:00'
  map:
    topLeftOrigin:
        # https://www.google.ca/maps/@45.6656598,-74.0651269,11.76z?entry=ttu
        lat: 45.6656598
        lon: -74.0651269
        alt: 11.76
    widthInKm: 40
    heightInKm: 20
  zoneSize:
    widthInKm: 10
    heightInKm: 10
  vehicleTypes:
    - Ambulance
    - Audi
    - Black_viper
    - Car
    - Mini_truck
    - Mini_van
    - Police
    - taxi
    - truck

collector:
  logging:
    enabled: true
    level: debug
  instances: 5
  httpPort: 7720
  geohashLength: 7 # 152.9m x 152.4m
  eventStore:
    type: noop # noop, memory, duckdb
  eventDispatcher:
    type: proxy
    dispatchers:
    - type: messageBus
    # - type: azureEventHub
    #   connectionString: EntityPath=move;Endpoint=sb://morgan-vehicle-events.servicebus.windows.net/;<REDACTED>
    #   sendDelayInMS: 5000
    #   sendParallelism: 5

  output:
    overwriteExistingFiles: false
    # flatLayout should be false for the Rust finder using local files and Datafusion lib
    # flatLayout should be true when the finder relies on Azure Sql Server queries
    flatLayout: false
    formats:
    - parquet
    # - csv
    # - arrow
    storage:
      # type: noop
      # type: s3

      # type: azure-blob
      # containerName: events
      # # connectionString: 

      type: file
      folder: ../../output/data

finder:
  logging:
    enabled: true
    level: info
  runtime: nodejs # nodejs, rust
  instances: 3
  httpPort: 7730
  defaultTimeoutInMS: 30000
  dataFormat: parquet
  parallelSearch: true
  useChunking: false
  messageChunkSize: 5000
  dataSource:
    type: file # will use Collector.output.storage
    # type: azureSql
    # connection:
    #   server: 'redacted-ondemand.sql.azuresynapse.net'
    #   database: 'vehicles'
    #   authentication: 
    #       type: 'azure-active-directory-service-principal-secret'
    #       options: 
    #           clientId: 'redacted'
    #           clientSecret: 'redacted'
    #           tenantId: 'redacted'
    #   options: 
    #       encrypt: true

viewer:
  logging:
    enabled: true
    level: debug
