hub:
  type: nats
  protocols:
    nats:
      servers:
      - localhost:4222
    websockets:
      servers:
      - ws://localhost:4243

generator:
  verbose: false
  generatorCount: 2
  vehicleCount: 100
  maxNumberOfEvents: 100000
  refreshIntervalInSecs: 5
  realtime: false
  sendFlush: true
  terminateCollector: true
  dataPartition:
    # type: id
    type: idGroup
    groupSize: 10
    # type: geohash
    # hashLength: 5

collector:
  verbose: false
  collectorCount: 2
  aggregationPeriodInMin: 10
  geohashLength: 5
  dataPartition:
    # type: collectorIndex
    # type: id
    type: idGroup
    groupSize: 10
    # type: geohash
    # hashLength: 5
  eventStore:
    type: noop # noop, memory, duckdb
  output:
    # type: noop
    type: file
    folder: ./output/data
    formats:
    - parquet

viewer:
  verbose: false
