{
 "title": "NATS Servers",
 "description": "NATS Server Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "OS Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gnatsd_varz_cpu{kubernetes_namespace=\"infra-morgan-vehicles\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gnatsd_varz_mem{kubernetes_namespace=\"infra-morgan-vehicles\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(gnatsd_varz_in_bytes{kubernetes_namespace=\"infra-morgan-vehicles\"}[5m])) by (server_id)",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "NATS Msgs In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(gnatsd_varz_in_msgs{kubernetes_namespace=\"infra-morgan-vehicles\"}[5m])) by (server_id)",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(gnatsd_varz_out_bytes{kubernetes_namespace=\"infra-morgan-vehicles\"}[5m])) by (server_id)",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "NATS Msgs Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(gnatsd_varz_out_msgs{kubernetes_namespace=\"infra-morgan-vehicles\"}[5m])) by (server_id)",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gnatsd_varz_connections{kubernetes_namespace=\"infra-morgan-vehicles\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gnatsd_varz_subscriptions{kubernetes_namespace=\"infra-morgan-vehicles\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gnatsd_varz_slow_consumers{kubernetes_namespace=\"infra-morgan-vehicles\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  }
 ]
}