{
 "title": "Vehicles",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(vehicles_message_sent_total[2m])) by (app_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(vehicles_message_received_total[2m])) by (app_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Partitions created/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(vehicles_collector_partitions_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Objects persisted/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(vehicles_collector_partitions_objects_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bytes persisted / sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(vehicles_collector_partitions_size[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(vehicles_collector_partitions_duration_secs_total[5m])) / sum(increase(vehicles_collector_partitions_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Search",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processed events/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum(rate(vehicles_search_processed_events_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Selected events/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum(rate(vehicles_search_selected_events_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processed bytes/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(vehicles_search_processed_bytes_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}